version: "3.8"

services:
  trading-bot:
    build: .
    volumes:
      - ./python_algorithms:/app/python_algorithms
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  streamlit:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - ./python_algorithms:/app/python_algorithms
      - ./.streamlit/secrets.toml:/root/.streamlit/secrets.toml
