version: "3.9"

services:
  trading-bot:
    build: .
    volumes:
      - ./python_algorithms:/app/python_algorithms
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  streamlit:
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./python_algorithms:/app/python_algorithms

