[package]
name = "crypto_trading_bot"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"  # Add this line


# [package]
# name = "crypto_trading_bot"
# version = "0.1.0"
# edition = "2018"

# [dependencies]
# pyo3 = { version = "0.15.1", features = ["extension-module"] }

